### ISSUE TITLE
Bookmark fails

### ISSUE THREAD

**Issue by miklb** [cweiske/tt-rss-micropub#1]
Attempting to post a bookmark, I get an error in tt-rss `Error creating post: Content, title, and excerpt are empty.`

Not sure what I'm missing, any suggestions?

Attempting to post a WordPress site with its own micropub endpoint.

**Comment by cweiske** [comment]
The Micropub request creating the bookmark only sets the `bookmark-of`property, and nothing else.

Seems wordpress' micropub endpoint does not like that and absolutely wants content, title and excerpt fields.

**Comment by miklb** [comment]
Ah, ok. Thanks.

**Comment by cweiske** [comment]
I've opened a bug report for the wordpress micropub plugin.

**Comment by cweiske** [comment]
Bookmarks are currently not supported by wordpress/wp-micropub.
