### ISSUE TITLE
Unable to add a new identity

### ISSUE THREAD

**Issue by eli-oat** [cweiske/tt-rss-micropub#2]
Whenever I attempt to add a new I identity I see an error message that says `No links found`

I'm running v15.7 of tt-rss, trying to add [eli.li](https://eli.li)

**Comment by cweiske** [comment]
It wants to extracts the Micropub links from the HTML, but that works here with https://eli.li - I get redirected to indieauth.com. Are you maybe running tt-rss  on the same server as https://eli.li?

**Comment by eli-oat** [comment]
Yeah. Same server but a completely different domain. 

Is both sites being on the same server what is causing the issue?

**Comment by cweiske** [comment]
could we meet in IRC to discuss this? #indieweb-dev

**Comment by eli-oat** [comment]
Sure thing, I have a bit of time right now, or can be on in a few hours. Talk soon and thanks!

**Comment by cweiske** [comment]
After improving error reporting, the following error is shown:

> Error fetching URL: https://eli.li

**Comment by eli-oat** [comment]
I've upgraded to PHP7, but am still seeing the same error. 

> Error fetching URL: https://eli.li 

@cweiske, in your comment you note it may be an SSL issue. I force HTTPS on my website via a redirect. Do you think that could be impacting the plugins ability to find the links on my website?

**Comment by eli-oat** [comment]
Updated from `v15.1` of tt-rss to` v17.4` and now everything seems to be working as anticipated.
