### ISSUE TITLE
Plugin doesn't include state parameter?

### ISSUE THREAD

**Issue by frankmeeuwsen** [cweiske/tt-rss-micropub#3]
I try to get the Micropub plugin from working on my Tiny Tiny RSS instance. When I use my demo-site (WordPress driven) and use [the author-URL](https://frankmeeuwsen.xyz/author/frankmeeuwsen/) as an identity I first get a message the state parameter is missing. I added it to the URL and I get to the authorization window of WordPress. When I click authorize I get an error "me" parameter missing. I add this as well to the identity URL in tt-rss but I still get this error. The full URL I use is https://frankmeeuwsen.xyz/author/frankmeeuwsen/?me=https%3A%2F%2Ffrankmeeuwsen.xyz%2F&state=123456
On the indieweb chat we already [had a discussion](https://chat.indieweb.org/dev/2019-08-31#bottom) and it looks like the plugin doesn't pass a state parameter?

**Comment by cweiske** [comment]
I don't use tt-rss anymore.
